### ISSUE TITLE
Is `tests/core/unit-tests/` designed to replace core/hooks ?

### ISSUE THREAD

**Issue by nil0x42** [unix-thrust/beurk#47]
if `tests/core/unit-tests/` is designed to test both hooks and internal api functions, then we need to update
`tests/core/check_needed_unit_tests.sh`.

if `tests/core/unit-tests/` is designed to only test internal api functions, then it might be better to rename it to something like `tests/core/internal-api/`

anyway, something should be done about it

@mzap, what do you think about it ?

**Comment by ghost** [comment]
As said in #49 I don't think we can mix in hooks, so a renaming to internal-api seems appropriate.
