### ISSUE TITLE
Missing ./build?

### ISSUE THREAD

**Issue by jdelman** [unix-thrust/beurk#97]
Pardon my ignorance - but I'm looking at the [wiki](https://github.com/unix-thrust/beurk/wiki/User's-Guide) which says to `./build beurk.conf` - but there is no `build` file in the directory. Am I missing some requirements?

**Comment by ghost** [comment]
Hi,

and thanks for the feedback. The wiki was outdated, we now use a Makefile to automate the build/installation. I updated the section, but to answer your question directly `make && make install` will do the trick.
